ProjectMVC2023/Controllers/AtorController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ProjectMVC2023.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DataLib;

namespace ProjectMVC2023.Controllers
{
    public class AtorController : Controller
    {
        private IWebHostEnvironment webHostEnvironment;
        
        public AtorController(IWebHostEnvironment hostEnvironment)
        {
            webHostEnvironment = hostEnvironment;
        }
        
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult cad(int eventoId) {
            AtorModel model = new AtorModel();
            model.EventoId = eventoId;
            return View(model);
        }


       

        [HttpPost]
        public IActionResult save(AtorModel atorModel)
        {
            if (ModelState.IsValid)
            {

                try
                {
                    atorModel.save(atorModel,webHostEnvironment);
                    ViewBag.mensagem = "Dados salvos com sucesso!";
                    ViewBag.classe = "alert-success";
                }
                catch (Exception ex)
                {

                    ViewBag.mensagem = "ops... Erro ao salvar!" + ex.Message + "/" + ex.InnerException;
                    ViewBag.classe = "alert-danger";
                }
            }
            else
            {
                ViewBag.mensagem = "ops... Erro ao salvar! verifique os campos";
                ViewBag.classe = "alert-danger";

            }

            return View("cad", atorModel);
        }


        public IActionResult list(int eventoId)
        {
            AtorModel atorModel = new AtorModel();
            List<AtorModel> list = atorModel.listRelated(eventoId);
            ViewBag.eventoId = eventoId;
            return View(list);//list por parametro para a view
        }


        public IActionResult change(int id)
        {
            AtorModel model = new AtorModel();
            Maybe<AtorModel> ator = model.select(id);
            if(ator.TryGetValue(out AtorModel data))
                return View("cad", data);
            else{
                ViewBag.mensagem = "Ator nao encontrado!";
                ViewBag.classe = "alert-danger";
                return View("cad", new AtorModel());       
            }
        }

        public IActionResult delete(int id)
        {
            AtorModel model = new AtorModel();
            try
            {
                Maybe<AtorModel> data = model.select(id);
                if(data is Maybe<AtorModel>.Some){
                    model.delete(id);
                    ViewBag.mensagem = "Dados excluidos com sucesso!";
                    ViewBag.classe = "alert-success";
                }else{
                    ViewBag.mensagem = "Ator nao encontrado!";
                    ViewBag.classe = "alert-danger";
                }
            }
            catch (Exception ex)
            {

                ViewBag.mensagem = "Ops... Não foi possível excluir!" + ex.Message;
                ViewBag.classe = "alert-danger";
            }

            return View("list", model.list());
        }
    }
}

ProjectMVC2023/Views/Ator/cad.cshtml
@model AtorModel
@{
    ViewData["Title"] = "cadastro";
}

<h1>cadastro</h1>

<form asp-action="save" asp-controller="Ator" method="post">
    <div class="row">
        <div class="col-12 form-group">
            <label asp-for="id"></label>
            <input readonly type="text" asp-for="id" class="form-control" />
            <span asp-validation-for="id" class="alert-danger"></span>
        </div>
        <div class="col-12 form-group">
            <label asp-for="nome"></label>
            <input type="text" asp-for="nome" class="form-control" />
            <span asp-validation-for="nome" class="alert-danger"></span>
        </div>
        <div class="col-12 form-group">
            <label asp-for="idade"></label>
            <input type="text" asp-for="idade" class="form-control" />
            <span asp-validation-for="idade" class="alert-danger"></span>
        </div>
        <div class="col-12 form-group">
            <label asp-for="papel"></label>
            <input type="text" asp-for="papel" class="form-control" />
            <span asp-validation-for="papel" class="alert-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="fileImage" class="control-label"></label>
            <div >
                <input asp-for="fileImage" type="file" id="customFile">
                <label class="custom-file-label" for="customFile">Escolha a imagem</label>
            </div>
            <span asp-validation-for="fileImage" class="text-danger"></span>
        </div>

        <div class="col-12 form-group">
            <input type="submit" class="btn btn-primary" value="Salvar" />
        </div>

        <span class="alert @ViewBag.classe">@ViewBag.mensagem</span>

    </div>
</form>




ProjectMVC2023/Views/Ator/list.cshtml
@model IEnumerable<AtorModel>
@{
    ViewData["Title"] = "listar";
}

<h1>listar</h1>

<span class="alert @ViewBag.classe">@ViewBag.mensagem</span>

<script>

function confirmExclusao(id) {
   if (confirm("Tem certeza que deseja excluir esse ator?")) {

       location.href ="/ator/delete/" + id;

   }
}
</script>

<a href="~/ator/cad/@ViewBag.eventoId" class="btn btn-info">
    Novo
</a>


<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Código</th>
            <th scope="col">Nome</th>
            <th scope="col">Idade</th>
            <th scope="col">Papel</th>
            <th scope="col">Foto</th>
            <th scope="col">Evento</th>
            <th scope="col">Alterar</th>
            <th scope="col">Excluir</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <th scope="row">@item.id</th>
                <td>@item.nome</td>
                <td>@item.idade</td>
                <td>@item.papel</td>
                <td>
                  <img src="~/Atores/@item.foto" class="rounded-circle" height="40" width="40" asp-append-version="true" />
                </td>
                <td></td>
                <td>
                    <a href="~/ator/change/@item.id" class="btn btn-primary">
                        Alterar
                    </a>
                </td>
                <td>
                    <a href="#" class="btn btn-primary" onclick="confirmExclusao(@item.id)">
                        Excluir
                    </a>
                </td>
            </tr>
        }


    </tbody>
</table>

