ProjectMVC2023/Controllers/EventoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ProjectMVC2023.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DataLib;

namespace ProjectMVC2023.Controllers
{
    public class EventoController : Controller
    {
        private IWebHostEnvironment webHostEnvironment;
        
        public EventoController(IWebHostEnvironment hostEnvironment)
        {
            webHostEnvironment = hostEnvironment;
        }
        
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult cad() {
            List<TipoModel> list = (new TipoModel()).list();
            ViewBag.listtipos = list.Select(t=>new SelectListItem() {
               Value = t.id.ToString(), Text = t.nome
            });
            return View(new EventoModel());
        }


       

        [HttpPost]
        public IActionResult save(EventoModel model)
        {
            if (ModelState.IsValid)
            {

                try
                {
                    EventoModel eventoModel = new EventoModel();
                    eventoModel.save(model,webHostEnvironment);
                    ViewBag.mensagem = "Dados salvos com sucesso!";
                    ViewBag.classe = "alert-success";
                }
                catch (Exception ex)
                {

                    ViewBag.mensagem = "ops... Erro ao salvar!" + ex.Message + "/" + ex.InnerException;
                    ViewBag.classe = "alert-danger";
                }
            }
            else
            {
                ViewBag.mensagem = "ops... Erro ao salvar! verifique os campos";
                ViewBag.classe = "alert-danger";

            }

            List<TipoModel> list = (new TipoModel()).list();
            ViewBag.listtipos = list.Select(t=>new SelectListItem() {
               Value = t.id.ToString(), Text = t.nome
            });

            return View("cad", model);
        }


        public IActionResult list()
        {
            EventoModel eventoModel = new EventoModel();
            List<EventoModel> list = eventoModel.list();
            return View(list);//list por parametro para a view
        }


        public IActionResult change(int id)
        {
            EventoModel model = new EventoModel();
            List<TipoModel> list = (new TipoModel()).list();
            ViewBag.listtipos = list.Select(t=>new SelectListItem() {
               Value = t.id.ToString(), Text = t.nome
            });
            Maybe<EventoModel> tipo = model.select(id);
            if(tipo.TryGetValue(out EventoModel data))
                return View("cad", data);
            else{
                ViewBag.mensagem = "Ator nao encontrado!";
                ViewBag.classe = "alert-danger";
                return View("cad", new EventoModel());       
            }
        }

        public IActionResult delete(int id)
        {
            EventoModel model = new EventoModel();
            try
            {
                Maybe<EventoModel> data = model.select(id);
                if(data is Maybe<EventoModel>.Some){
                    model.delete(id);
                    ViewBag.mensagem = "Dados excluidos com sucesso!";
                    ViewBag.classe = "alert-success";
                }else{
                    ViewBag.mensagem = "Evento nao encontrado!";
                    ViewBag.classe = "alert-danger";
                }
            }
            catch (Exception ex)
            {

                ViewBag.mensagem = "Ops... Não foi possível excluir!" + ex.Message;
                ViewBag.classe = "alert-danger";
            }

            return View("list", model.list());
        }
    }
}

ProjectMVC2023/Views/Evento/cad.cshtml
@model EventoModel
@{
    ViewData["Title"] = "cadastro";
}

<h1>cadastro</h1>

<form asp-action="save" asp-controller="Evento" method="post">
    <div class="row">
        <div class="col-12 form-group">
            <label asp-for="id"></label>
            <input readonly type="text" asp-for="id" class="form-control" />
            <span asp-validation-for="id" class="alert-danger"></span>
        </div>
        <div class="col-12 form-group">
            <label asp-for="nome"></label>
            <input type="text" asp-for="nome" class="form-control" />
            <span asp-validation-for="nome" class="alert-danger"></span>
        </div>
        <div class="col-12 form-group">
            <label asp-for="duracao"></label>
            <input type="text" asp-for="duracao" class="form-control" />
            <span asp-validation-for="duracao" class="alert-danger"></span>
        </div>
        <div class="col-12 form-group">
            <label asp-for="restricao_idade"></label>
            <input type="text" asp-for="restricao_idade" class="form-control" />
            <span asp-validation-for="restricao_idade" class="alert-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="fileImage" class="control-label"></label>
            <div >
                <input asp-for="fileImage" type="file" id="customFile">
                <label class="custom-file-label" for="customFile">Escolha a imagem</label>
            </div>
            <span asp-validation-for="fileImage" class="text-danger"></span>
        </div>


        <div class="col-12 form-group">
            <label asp-for="TipoId"></label>
            <select class="form-control" asp-for="TipoId" asp-items="@ViewBag.listtipos">
                <option>Selecione um tipo.....</option>
            </select>
            <span asp-validation-for="TipoId" class="alert-danger"></span>
        </div>

        <div class="col-12 form-group">
            <input type="submit" class="btn btn-primary" value="Salvar" />
        </div>

        <span class="alert @ViewBag.classe">@ViewBag.mensagem</span>

    </div>
</form>




ProjectMVC2023/Views/Evento/list.cshtml
@model IEnumerable<EventoModel>
@{
    ViewData["Title"] = "listar";
}

<h1>listar</h1>

<span class="alert @ViewBag.classe">@ViewBag.mensagem</span>

<script>

function confirmExclusao(id) {
   if (confirm("Tem certeza que deseja excluir esse evento?")) {

       location.href ="/evento/delete/" + id;

   }
}
</script>

<a href="~/evento/cad" class="btn btn-info">
    Novo
</a>


<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Código</th>
            <th scope="col">Nome</th>
            <th scope="col">Duração</th>
            <th scope="col">Restrição de idade</th>
            <th scope="col">Cartaz</th>
            <th scope="col">Tipo</th>
            <th scope="col">Atores</th>
            <th scope="col">Sessões</th>
            <th scope="col">Alterar</th>
            <th scope="col">Excluir</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <th scope="row">@item.id</th>
                <td>@item.nome</td>
                <td>@item.duracao</td>
                <td>@item.restricao_idade</td>
                <td>
                  <img src="~/Cartazes/@item.cartaz" class="rounded-circle" height="40" width="40" asp-append-version="true" />
                </td>
                <td></td>
                <td>
                    <a href="~/ator/list/@item.id" class="btn btn-primary">
                        Atores
                    </a>
                </td>
                <td>
                    <a href="~/sessao/list/@item.id" class="btn btn-primary">
                        Sessões
                    </a>
                </td>
                <td>
                    <a href="~/evento/change/@item.id" class="btn btn-primary">
                        Alterar
                    </a>
                </td>
                <td>
                    <a href="#" class="btn btn-primary" onclick="confirmExclusao(@item.id)">
                        Excluir
                    </a>
                </td>
            </tr>
        }


    </tbody>
</table>

