ProjectMVC2023/Controllers/SessaoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ProjectMVC2023.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DataLib;

namespace ProjectMVC2023.Controllers
{
    public class SessaoController : Controller
    {
        
        
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult cad(int eventoId) {
            SessaoModel model = new SessaoModel();
            model.EventoId = eventoId;
            List<SalaModel> list = (new SalaModel()).list();
            ViewBag.listsalas = list.Select(s=>new SelectListItem() {
               Value = s.id.ToString(), Text = s.nome
            });
            return View(model);
        }


       

        [HttpPost]
        public IActionResult save(SessaoModel model)
        {
            if (ModelState.IsValid)
            {

                try
                {
                    SessaoModel sessaoModel = new SessaoModel();
                    sessaoModel.save(model);
                    ViewBag.mensagem = "Dados salvos com sucesso!";
                    ViewBag.classe = "alert-success";
                }
                catch (Exception ex)
                {

                    ViewBag.mensagem = "ops... Erro ao salvar!" + ex.Message + "/" + ex.InnerException;
                    ViewBag.classe = "alert-danger";
                }
            }
            else
            {
                ViewBag.mensagem = "ops... Erro ao salvar! verifique os campos";
                ViewBag.classe = "alert-danger";

            }

            List<SalaModel> list = (new SalaModel()).list();
            ViewBag.listsalas = list.Select(s=>new SelectListItem() {
               Value = s.id.ToString(), Text = s.nome
            });
            return View("cad", model);
        }


        public IActionResult list(int eventoId)
        {
            SessaoModel sessaoModel = new SessaoModel();
            List<SessaoModel> list = sessaoModel.listRelated(eventoId);
            ViewBag.eventoId = eventoId;
            return View(list);//list por parametro para a view
        }


        public IActionResult change(int id)
        {
            SessaoModel model = new SessaoModel();
            List<SalaModel> list = (new SalaModel()).list();
            ViewBag.listsalas = list.Select(s=>new SelectListItem() {
               Value = s.id.ToString(), Text = s.nome
            });
            Maybe<SessaoModel> ator = model.select(id);
            if(ator.TryGetValue(out SessaoModel data))
                return View("cad", data);
            else{
                ViewBag.mensagem = "Sessao nao encontrada!";
                ViewBag.classe = "alert-danger";
                return View("cad", new SessaoModel());       
            }
        }

        public IActionResult delete(int id)
        {
            SessaoModel model = new SessaoModel();
            try
            {
                Maybe<SessaoModel> data = model.select(id);
                if(data is Maybe<SessaoModel>.Some){
                    model.delete(id);
                    ViewBag.mensagem = "Dados excluidos com sucesso!";
                    ViewBag.classe = "alert-success";
                }else{
                    ViewBag.mensagem = "Sessao nao encontrada!";
                    ViewBag.classe = "alert-danger";
                }
            }
            catch (Exception ex)
            {

                ViewBag.mensagem = "Ops... Não foi possível excluir!" + ex.Message;
                ViewBag.classe = "alert-danger";
            }

            return View("list", model.list());
        }
    }
}

ProjectMVC2023/Views/Sessao/cad.cshtml
@model ProjectMVC2023.Models.SessaoModel
@{
    ViewData["Title"] = "cadastro";
}

<h1>cadastro</h1>
<form asp-controller="Sessao" asp-action="save" method="post">
    <div class="row">
        <div class="col-12 form-group">
            <label asp-for="id"></label>
            <input readonly type="text" asp-for="id" class="form-control" />
            <span asp-validation-for="id" class="alert-danger"></span>
        </div>
        <div class="col-12 form-group">
            <label asp-for="EventoId"></label>
            <input readonly type="text" asp-for="EventoId" class="form-control" />
            <span asp-validation-for="EventoId" class="alert-danger"></span>
        </div>
        <div class="col-12 form-group">
            <label asp-for="nome"></label>
            <input type="text" asp-for="nome" class="form-control" />
            <span asp-validation-for="nome" class="alert-danger"></span>
        </div>
        <div class="col-12 form-group">
            <label asp-for="valor"></label>
            <input type="text" asp-for="valor" class="form-control" />
            <span asp-validation-for="valor" class="alert-danger"></span>
        </div>
        <div class="col-12 form-group">
            <label asp-for="data_hora_inicio"></label>
            <input type="date" asp-for="data_hora_inicio" class="form-control" />
            <span asp-validation-for="data_hora_inicio" class="alert-danger"></span>
        </div>
        <div class="col-12 form-group">
            <label asp-for="data_hora_fim"></label>
            <input type="date" asp-for="data_hora_fim" class="form-control" />
            <span asp-validation-for="data_hora_fim" class="alert-danger"></span>
        </div>
        <div class="col-12 form-group">
            <label asp-for="SalaId"></label>
            <select class="form-control" asp-for="SalaId" asp-items="@ViewBag.listsalas">
                <option>Selecione uma sala.....</option>
            </select>
            <span asp-validation-for="SalaId" class="alert-danger"></span>
        </div>
        <div class="col-12 form-group">
            <input type="submit" class="btn btn-primary" value="Salvar" />
        </div>
        
            <span class="alert @ViewBag.classe">@ViewBag.mensagem</span>
        
    </div>
</form>


ProjectMVC2023/Views/Sessao/list.cshtml
@model IEnumerable<SessaoModel>
@{
    ViewData["Title"] = "listar";
}

<h1>listar</h1>

<span class="alert @ViewBag.classe">@ViewBag.mensagem</span>

<script>

function confirmExclusao(id) {
   if (confirm("Tem certeza que deseja excluir essa sessão?")) {
    
       location.href ="/sessao/delete/" + id;
     
   }
}
</script>

<a href="~/sessao/cad/@ViewBag.eventoId" class="btn btn-info">
    Novo
</a>


<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Código</th>
            <th scope="col">Nome</th>
            <th scope="col">Sala</th>
            <th scope="col">Alterar</th>
            <th scope="col">Excluir</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <th scope="row">@item.id</th>
                <td>@item.nome</td>
                <td>R$ @item.valor</td>
                <td>@item.data_hora_inicio</td>
                <td>@item.data_hora_fim</td>
                <td>@item.nomeEvento</td>
                <td>@item.nomeSala</td>
                <td>
                    <a href="~/sessao/change/@item.id" class="btn btn-primary" >
                        Alterar
                    </a>
                </td>
                <td>
                    <a href="#" class="btn btn-primary" onclick="confirmExclusao(@item.id)">
                        Excluir
                    </a>
                </td>
            </tr>
        }


    </tbody>
</table>