ProjectMVC2023/Controllers/DivisaoController.cs
using Microsoft.AspNetCore.Mvc;
using ProjectMVC2023.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DataLib;

namespace ProjectMVC2023.Controllers
{
    public class DivisaoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult cad() {
            return View(new DivisaoModel());
        }

        [HttpPost]
        public IActionResult save(DivisaoModel model) {
            if (ModelState.IsValid)
            {

                try
                {
                    DivisaoModel divisaoModel = new DivisaoModel();
                    divisaoModel.save(model);
                    ViewBag.mensagem = "Dados salvos com sucesso!";
                    ViewBag.classe = "alert-success";
                }
                catch (Exception ex)
                {

                    ViewBag.mensagem = "ops... Erro ao salvar!" + ex.Message + "/" + ex.InnerException;
                    ViewBag.classe = "alert-danger";
                }
            }
            else
            {
                ViewBag.mensagem = "ops... Erro ao salvar! verifique os campos";
                ViewBag.classe = "alert-danger";

            }

            return View("cad", model);
        }


        public IActionResult list()
        {
            DivisaoModel divisaoModel = new DivisaoModel();
            List<DivisaoModel> list = divisaoModel.list();
            return View(list);//lista por parametro para a view
        }


        public IActionResult change(int id) {
            DivisaoModel model = new DivisaoModel();
            Maybe<DivisaoModel> divisao = model.select(id);
            if(divisao.TryGetValue(out DivisaoModel data))
                return View("cad", data);
            else{
                ViewBag.mensagem = "Ator nao encontrado!";
                ViewBag.classe = "alert-danger";
                return View("cad", new DivisaoModel());       
            }
        }

        public IActionResult delete(int id) {
            DivisaoModel model = new DivisaoModel();
            try
            {
                Maybe<DivisaoModel> data = model.select(id);
                if(data is Maybe<DivisaoModel>.Some){
                    model.delete(id);
                    ViewBag.mensagem = "Dados excluidos com sucesso!";
                    ViewBag.classe = "alert-success";
                }else{
                    ViewBag.mensagem = "Divisao nao encontrada!";
                    ViewBag.classe = "alert-danger";
                }
            }
            catch (Exception ex)
            {

                ViewBag.mensagem = "Ops... Não foi possível excluir!" + ex.Message;
                ViewBag.classe = "alert-danger";
            }

            return View("list", model.list());
        }
    }
}

ProjectMVC2023/Views/Divisao/cad.cshtml
@model ProjectMVC2023.Models.DivisaoModel
@{
    ViewData["Title"] = "cadastro";
}

<h1>cadastro</h1>
<form asp-controller="Divisao" asp-action="save" method="post">
    <div class="row">
        <div class="col-12 form-group">
            <label asp-for="id"></label>
            <input readonly type="text" asp-for="id" class="form-control" />
            <span asp-validation-for="id" class="alert-danger"></span>
        </div>
        <div class="col-12 form-group">
            <label asp-for="nome"></label>
            <input type="text" asp-for="nome" class="form-control" />
            <span asp-validation-for="nome" class="alert-danger"></span>
        </div>
        <div class="col-12 form-group">
            <label asp-for="escala"></label>
            <input type="text" asp-for="escala" class="form-control" />
            <span asp-validation-for="escala" class="alert-danger"></span>
        </div>
        <div class="col-12 form-group">
            <label asp-for="restricao_idade"></label>
            <input type="text" asp-for="restricao_idade" class="form-control" />
            <span asp-validation-for="restricao_idade" class="alert-danger"></span>
        </div>
        <div class="col-12 form-group">
            <input type="submit" class="btn btn-primary" value="Salvar" />
        </div>
        
            <span class="alert @ViewBag.classe">@ViewBag.mensagem</span>
        
    </div>
</form>


ProjectMVC2023/Views/Divisao/list.cshtml
@model IEnumerable<DivisaoModel>
@{
    ViewData["Title"] = "listar";
}

<h1>listar</h1>

<span class="alert @ViewBag.classe">@ViewBag.mensagem</span>

<script>

function confirmExclusao(id) {
   if (confirm("Tem certeza que deseja excluir esse divisão?")) {
    
       location.href ="/divisao/delete/" + id;
     
   }
}
</script>

<a href="~/divisao/cad" class="btn btn-info">
    Novo
</a>


<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Código</th>
            <th scope="col">Nome</th>
            <th scope="col">Escala</th>
            <th scope="col">Restrição de idade</th>
            <th scope="col">Alterar</th>
            <th scope="col">Excluir</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <th scope="row">@item.id</th>
                <td>@item.nome</td>
                <td>@item.escala</td>
                <td>@item.restricao_idade</td>
                <td>
                    <a href="~/divisao/change/@item.id" class="btn btn-primary" >
                        Alterar
                    </a>
                </td>
                <td>
                    <a href="#" class="btn btn-primary" onclick="confirmExclusao(@item.id)">
                        Excluir
                    </a>
                </td>
            </tr>
        }


    </tbody>
</table>